---

disabled_rules:
  - file_length
  - line_length
  - function_body_length

  - nesting
  - cyclomatic_complexity
  - todo

  - force_try
  - force_cast
  - void_return
  - trailing_comma
  - shorthand_operator

opt_in_rules:
  - first_where
  - last_where
  - sorted_first_last
  - empty_count
  - empty_string

included:
  - Form
  - FormTests
  - Examples

identifier_name:
  excluded: [id, i, vc, at, to, l, r, j]
  severity: warning
  max_length: 55
