version: 2

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

jobs:
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint --strict

  test-iOS:
    macos:
      xcode: "11.0.0"
    steps:
      - checkout
      - run:
          name: test iOS
          command: |
            set -o pipefail
            xcodebuild -version
            xcodebuild -showsdks
            swift -version
            sh build.sh test-iOS

  test-iOS12:
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - run:
          name: test iOS
          command: |
            set -o pipefail
            xcodebuild -version
            xcodebuild -showsdks
            swift -version
            IOS_SDK="iphonesimulator12.2" \
                IOS_DESTINATION_PHONE="OS=12.2,name=iPhone Xs" \
                sh build.sh test-iOS

  examples:
    macos:
      xcode: "11.0.0"
    steps:
      - checkout
      - run:
          name: examples
          command: |
            set -o pipefail
            xcodebuild -version
            xcodebuild -showsdks
            swift -version
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cfk
            sh build.sh examples

workflows:
  version: 2
  build-and-test:
    jobs:
      - swiftlint
      - test-iOS:
          requires:
            - swiftlint
      - test-iOS12:
          requires:
            - swiftlint
      - examples:
          requires:
            - swiftlint
